Ext.Require("Init/_InitGlobals.lua")
Ext.Require("CompatibilitySupport/SubclassSupport/_IntegratedSubClasses.lua")
Ext.Require("CompatibilitySupport/_Strings.lua")
Ext.Require("CompatibilitySupport/_Globals.lua")
Ext.Require("CompatibilitySupport/_Utils.lua")
Ext.Require("CompatibilitySupport/SubclassSupport/_SubclassCompatibility.lua")
Ext.Require("CompatibilitySupport/SelectorSupport/_SelectorCompatibility.lua")
Ext.Require("CompatibilitySupport/StringSupport/_ProgressionStringCompatibility.lua")
Ext.Require("CompatibilitySupport/ListsSupport/_ListCompatibility.lua")
Ext.Require("CompatibilitySupport/API.lua")

Utils.Info(Strings.LOADED_REQUIRED_FILES)

Ext.Require("Init/_InitClasses.lua")
Ext.Require("Init/_InitIntegratedSubclasses.lua")
