Strings.INFO_TAG = "[INFO]: "
Strings.ERROR_TAG = "[ERROR]: "
Strings.LOADED_REQUIRED_FILES = "Required Files loaded."
Strings.LOADED_MAIN_CLASSES = "Main Classes Added."
Strings.UNFINISHED_API_WARNING = "Using an Unfinished API. Proceed at your own risk."
Strings.INVALID_CLASS_PROVIDED = "Invalid Class Supplied. Provide a UUID, or Insert the Parent Class into Globals.ClassUUIDs"