Strings.INFO_TAG = "[INFO]: "
Strings.WARNING_TAG = "[WARNING]: "
Strings.ERROR_TAG = "[ERROR]: "
Strings.LOADED_REQUIRED_FILES = "Required Files loaded."
Strings.LOADED_MAIN_CLASSES = "Main Classes Added."
Strings.UNFINISHED_API_WARNING = "Using an Unfinished API. Proceed at your own risk."
Strings.INVALID_CLASS_PROVIDED =
"Invalid Class Supplied. Provide a UUID, or Insert the Parent Class into Globals.ClassUUIDs"
Strings.ERROR_FAILED_VALIDATION = "Validation Failure. Compatibility Framework skipping support for mod Because: "
Strings.ERROR_DISABLED_API = "This API Call is not currently enabled."
Strings.ERROR_EMPTY_PAYLOAD = "Payload is empty."
Strings.ERROR_INVALID_PROGRESSION_TYPE = "Invalid String Type."
Strings.ERROR_INVALID_BOOLEAN_TYPE = "Unsupported Boolean key: "
Strings.ERROR_INVALID_LIST_TYPE = "Invalid List Type."
Strings.ERROR_LIST_NOT_FOUND = "Target list not found!"
Strings.ERROR_EMPTY_ARRAYS = "Arrays are both empty."
Strings.ERROR_MOD_NOT_LOADED = "Mod isn't loaded. Expected UUID: "
Strings.ERROR_PROGRESSION_EXISTS_IN_DICTIONARY = "Progression is already defined in Globals.Progressions"
Strings.ERROR_FEAT_EXISTS_IN_DICTIONARY = "Feat is already defined in Globals.Feats"
Strings.ERROR_ACTION_RESOURCE_EXISTS_IN_DICTIONARY = "Action Resource is already defined in Globals.ActionResources"
Strings.ERROR_ACTION_RESOURCE_GROUP_EXISTS_IN_DICTIONARY =
"Action Resource Group is already defined in Globals.ActionResourceGroups"
Strings.ERROR_LIST_EXISTS_IN_DICTIONARY_EQUIPMENT = "List is already defined in Globals.EquipmentLists."
Strings.ERROR_LIST_EXISTS_IN_DICTIONARY_ABILITY = "List is already defined in Globals.AbilityLists."
Strings.ERROR_LIST_EXISTS_IN_DICTIONARY_SKILL = "List is already defined in Globals.SkillLists."
Strings.ERROR_LIST_EXISTS_IN_DICTIONARY_SPELL = "List is already defined in Globals.SpellLists."
Strings.ERROR_LIST_EXISTS_IN_DICTIONARY_PASSIVE = "List is already defined in Globals.PassiveLists."
Strings.ERROR_PAYLOAD_MISSING_FIELD = "Payload is missing expected field "
Strings.ERROR_ACTION_RESOURCE_DOES_NOT_EXIST_IN_DICTIONARY = "Action Resource is not defined in Globals.ActionResources"
Strings.ERROR_ACTION_RESOURCE_GROUP_DOES_NOT_EXIST_IN_DICTIONARY =
"Action Resource Group is not defined in Globals.ActionResourceGroups"
Strings.ERROR_FEAT_DOES_NOT_EXIST_IN_DICTIONARY = "Feat is not defined in Globals.Feats"
Strings.ERROR_PROGRESSION_DOES_NOT_EXIST_IN_DICTIONARY = "Progression is not defined in Globals.Progressions"
Strings.ERROR_LIST_DOES_NOT_EXIST_IN_DICTIONARY_ABILITIES = "List is not defined in Globals.AbilityLists"
Strings.ERROR_LIST_DOES_NOT_EXIST_IN_DICTIONARY_EQUIPMENT = "List is not defined in Globals.EquipementLists"
Strings.ERROR_LIST_DOES_NOT_EXIST_IN_DICTIONARY_SKILL = "List is not defined in Globals.SkillLists"
Strings.ERROR_LIST_DOES_NOT_EXIST_IN_DICTIONARY_SPELL = "List is not defined in Globals.SpellLists"
Strings.ERROR_LIST_DOES_NOT_EXIST_IN_DICTIONARY_PASSIVE = "List is not defined in Globals.PassiveLists"
Strings.ERROR_TARGET_NOT_FOUND = "Target Object not found!"
Strings.ERROR_RACE_DATA_NOT_FOUND = "Race Data not found!"
Strings.WARN_INVALID_SPELLDATA_SUPPLIED = "The following Stats Data was either supplied to CF or manually defined in *List.lsx, but does not exist: "
Strings.WARN_SERVER_FUNCTION_NO_LONGER_REQUIRED =
"Unnecessary call from external mod to Compatibility Framework API from BootstrapServer.lua. THIS IS NOT A BUG. The mod using Compatibility Framework API can remove their API call from BootstrapServer file, leaving it in the BootstrapClient file."
Strings.WARN_LAST_CALL =
"StatsLoaded Complete. Any mods calling the CF API after this point may not appear. Please contact the developer of any missing mods and inform them to switch their CF API call to happen on StatsLoaded instead of on SessionLoaded."
Strings.LATE_LOADER_PREFIX = "The following mods are attempting to call Compatibility Framework API too late for it to take effect: "